name = "IsotopicCalc"
uuid = "5554e927-0bdd-4e37-b621-d0b49d571e7b"
version = "0.6.0"
authors = ["Tomas Mikoviny <tomasmi@uio.no> and contributors"]

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
JSON = "0.21, 1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
